# Generated by Django 4.2.20 on 2025-03-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link do GitHub'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem de Perfil'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='resume_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Currículo'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project/images/', verbose_name='Imagem do Projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, to='home_page.skill', verbose_name='Habilidades Utilizadas'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título do Projeto'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Classe do Ícone (FontAwesome)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Habilidade'),
        ),
        migrations.AlterField(
            model_name='styleconfig',
            name='css_file',
            field=models.FileField(blank=True, null=True, upload_to='css/', verbose_name='Arquivo CSS'),
        ),
        migrations.AlterField(
            model_name='styleconfig',
            name='theme_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Tema'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Classe do Ícone (FontAwesome)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.TextField(blank=True, null=True, verbose_name='Citação'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='source_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Informação da Fonte'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Fonte'),
        ),
    ]
