# Generated by Django 4.2.20 on 2025-03-11 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_alter_aboutme_bio_alter_aboutme_github_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinicaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Predefinição')),
                ('objetivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Objetivo (Ex: Vaga Python, Vaga PHP)')),
                ('depoimentos', models.ManyToManyField(blank=True, to='home_page.testimonial', verbose_name='Depoimentos Destacados')),
                ('habilidades', models.ManyToManyField(blank=True, to='home_page.skill', verbose_name='Habilidades Destacadas')),
                ('projetos', models.ManyToManyField(blank=True, to='home_page.project', verbose_name='Projetos Destacados')),
                ('sobre_mim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_page.aboutme', verbose_name='Sobre Mim')),
                ('tema_css', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_page.styleconfig', verbose_name='Tema CSS')),
            ],
            options={
                'verbose_name': 'Predefinição Geral',
                'verbose_name_plural': 'Predefinições Gerais',
            },
        ),
    ]
