# Generated by Django 4.2.20 on 2025-03-12 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_predefinicaogeral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do ícone do Font Awesome (ex: fab fa-python)', max_length=50, unique=True)),
                ('tamanho', models.CharField(blank=True, help_text='Tamanho do ícone (ex: fa-3x)', max_length=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='project_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='source_info',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='source_name',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description',
            field=models.TextField(default='', help_text='Descrição detalhada do projeto ou depoimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default=' ', help_text='Nome do projeto ou título do depoimento', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='project_link',
            field=models.URLField(blank=True, help_text='Link para o projeto (ex: GitHub)', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='technologies',
            field=models.CharField(default=' ', help_text='Tecnologias usadas (ex: Python, PyAutoGUI, PyQT, Pandas)', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='icone',
            field=models.ForeignKey(blank=True, help_text='Ícone associado ao depoimento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_page.icone'),
        ),
    ]
